version: '3.9'

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    restart: always
    volumes:
      - redis:/data
    networks:
      - backend
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis:redis:6379
    ports:
      - '8081:8081'
    networks:
      - backend
    depends_on:
      - redis

  postgres:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${TYPEORM_PORT}:${TYPEORM_PORT}"
    hostname: db
    networks:
      - backend

  backend:
    container_name: pokemon
    build:
      context: ./
    depends_on:
      - redis
      - redis-commander
      - postgres
    restart: always
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - backend

volumes:
  redis:
  postgres:

networks:
  backend:
